//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("IGWS", ClrNamespace="IGWS")]
[assembly: System.Runtime.Serialization.ContractNamespaceAttribute("", ClrNamespace="GeneratedNamespace1")]



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="IGWS", ConfigurationName="IMessages")]
public interface IMessages
{
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetReturnMessages", ReplyAction="IGWS/IMessages/GetReturnMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetReturnMessagesIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetReturnMessagesResult GetReturnMessages(string accessID, string password, ReturnMessageFilter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetReturnMessages", ReplyAction="IGWS/IMessages/GetReturnMessagesResponse")]
    System.Threading.Tasks.Task<GetReturnMessagesResult> GetReturnMessagesAsync(string accessID, string password, ReturnMessageFilter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetSubaccountsReturnMessages", ReplyAction="IGWS/IMessages/GetSubaccountsReturnMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetSubaccountsReturnMessagesIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetReturnMessagesResult GetSubaccountsReturnMessages(string accessID, string password, string startUTC, bool includeRawPayload, bool includeType);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetSubaccountsReturnMessages", ReplyAction="IGWS/IMessages/GetSubaccountsReturnMessagesResponse")]
    System.Threading.Tasks.Task<GetReturnMessagesResult> GetSubaccountsReturnMessagesAsync(string accessID, string password, string startUTC, bool includeRawPayload, bool includeType);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitForwardMessages", ReplyAction="IGWS/IMessages/SubmitForwardMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/SubmitForwardMessagesIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SubmitMessagesResult SubmitForwardMessages(string accessID, string password, ForwardMessage[] messages);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitForwardMessages", ReplyAction="IGWS/IMessages/SubmitForwardMessagesResponse")]
    System.Threading.Tasks.Task<SubmitMessagesResult> SubmitForwardMessagesAsync(string accessID, string password, ForwardMessage[] messages);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitForwardMessageToMultipleDestinations", ReplyAction="IGWS/IMessages/SubmitForwardMessageToMultipleDestinationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/SubmitForwardMessageToMultipleDestinationsIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SubmitMessagesResult SubmitForwardMessageToMultipleDestinations(string accessID, string password, ForwardMessage message, string[] destinations);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitForwardMessageToMultipleDestinations", ReplyAction="IGWS/IMessages/SubmitForwardMessageToMultipleDestinationsResponse")]
    System.Threading.Tasks.Task<SubmitMessagesResult> SubmitForwardMessageToMultipleDestinationsAsync(string accessID, string password, ForwardMessage message, string[] destinations);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitMessageCancelations", ReplyAction="IGWS/IMessages/SubmitMessageCancelationsResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/SubmitMessageCancelationsIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    SubmitMessagesResult SubmitMessageCancelations(string accessID, string password, int[] fwMessageIDs);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/SubmitMessageCancelations", ReplyAction="IGWS/IMessages/SubmitMessageCancelationsResponse")]
    System.Threading.Tasks.Task<SubmitMessagesResult> SubmitMessageCancelationsAsync(string accessID, string password, int[] fwMessageIDs);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetForwardStatuses", ReplyAction="IGWS/IMessages/GetForwardStatusesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetForwardStatusesIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetForwardStatusesResult GetForwardStatuses(string accessID, string password, ForwardStatusFilter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetForwardStatuses", ReplyAction="IGWS/IMessages/GetForwardStatusesResponse")]
    System.Threading.Tasks.Task<GetForwardStatusesResult> GetForwardStatusesAsync(string accessID, string password, ForwardStatusFilter filter);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetForwardMessages", ReplyAction="IGWS/IMessages/GetForwardMessagesResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetForwardMessagesIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetForwardMessagesResult GetForwardMessages(string accessID, string password, int[] fwMessageIDs, string subaccountID);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetForwardMessages", ReplyAction="IGWS/IMessages/GetForwardMessagesResponse")]
    System.Threading.Tasks.Task<GetForwardMessagesResult> GetForwardMessagesAsync(string accessID, string password, int[] fwMessageIDs, string subaccountID);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/IGWSInformation", ReplyAction="IGWS/IMessages/IGWSInformationResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/IGWSInformationIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    IGWSInformationResponse IGWSInformation(string accessID, string password, bool getErrorCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/IGWSInformation", ReplyAction="IGWS/IMessages/IGWSInformationResponse")]
    System.Threading.Tasks.Task<IGWSInformationResponse> IGWSInformationAsync(string accessID, string password, bool getErrorCodes);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetTerminalsInfo", ReplyAction="IGWS/IMessages/GetTerminalsInfoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetTerminalsInfoIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetTerminalsInfoResult GetTerminalsInfo(string accessID, string password, string subaccountID, string sinceID, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetTerminalsInfo", ReplyAction="IGWS/IMessages/GetTerminalsInfoResponse")]
    System.Threading.Tasks.Task<GetTerminalsInfoResult> GetTerminalsInfoAsync(string accessID, string password, string subaccountID, string sinceID, int pageSize);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetBroadcastInfos", ReplyAction="IGWS/IMessages/GetBroadcastInfosResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetBroadcastInfosIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetBroadcastInfoResult GetBroadcastInfos(string accessID, string password, string subaccountID);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetBroadcastInfos", ReplyAction="IGWS/IMessages/GetBroadcastInfosResponse")]
    System.Threading.Tasks.Task<GetBroadcastInfoResult> GetBroadcastInfosAsync(string accessID, string password, string subaccountID);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetSubaccountInfos", ReplyAction="IGWS/IMessages/GetSubaccountInfosResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(GeneratedNamespace1.IGWSFault), Action="IGWS/IMessages/GetSubaccountInfosIGWSFaultFault", Name="IGWSFault", Namespace="")]
    [System.ServiceModel.XmlSerializerFormatAttribute()]
    GetSubaccountInfoResult GetSubaccountInfos(string accessID, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="IGWS/IMessages/GetSubaccountInfos", ReplyAction="IGWS/IMessages/GetSubaccountInfosResponse")]
    System.Threading.Tasks.Task<GetSubaccountInfoResult> GetSubaccountInfosAsync(string accessID, string password);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ReturnMessageFilter
{
    
    private string startUTCField;
    
    private bool includeRawPayloadField;
    
    private string subAccountIDField;
    
    private System.Nullable<bool> includeTypeField;
    
    private bool includeTypeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string StartUTC
    {
        get
        {
            return this.startUTCField;
        }
        set
        {
            this.startUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool IncludeRawPayload
    {
        get
        {
            return this.includeRawPayloadField;
        }
        set
        {
            this.includeRawPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SubAccountID
    {
        get
        {
            return this.subAccountIDField;
        }
        set
        {
            this.subAccountIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
    public System.Nullable<bool> IncludeType
    {
        get
        {
            return this.includeTypeField;
        }
        set
        {
            this.includeTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IncludeTypeSpecified
    {
        get
        {
            return this.includeTypeFieldSpecified;
        }
        set
        {
            this.includeTypeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class SubaccountInfo
{
    
    private string accountIDField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string AccountID
    {
        get
        {
            return this.accountIDField;
        }
        set
        {
            this.accountIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetSubaccountInfoResult
{
    
    private int errorIDField;
    
    private SubaccountInfo[] subaccountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public SubaccountInfo[] Subaccounts
    {
        get
        {
            return this.subaccountsField;
        }
        set
        {
            this.subaccountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class BroadcastInfo
{
    
    private string idField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetBroadcastInfoResult
{
    
    private int errorIDField;
    
    private BroadcastInfo[] broadcastInfosField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public BroadcastInfo[] BroadcastInfos
    {
        get
        {
            return this.broadcastInfosField;
        }
        set
        {
            this.broadcastInfosField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class TerminalInfo
{
    
    private string primeIDField;
    
    private string descriptionField;
    
    private string lastRegistrationUTCField;
    
    private string regionNameField;
    
    private string mTSNField;
    
    private string iMEIField;
    
    private string mEIDField;
    
    private string mACField;
    
    private string pairedTerminalPrimeIDField;
    
    private string lastMTBPUTCField;
    
    private string lastMTWSUTCField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string PrimeID
    {
        get
        {
            return this.primeIDField;
        }
        set
        {
            this.primeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string LastRegistrationUTC
    {
        get
        {
            return this.lastRegistrationUTCField;
        }
        set
        {
            this.lastRegistrationUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string RegionName
    {
        get
        {
            return this.regionNameField;
        }
        set
        {
            this.regionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string MTSN
    {
        get
        {
            return this.mTSNField;
        }
        set
        {
            this.mTSNField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string IMEI
    {
        get
        {
            return this.iMEIField;
        }
        set
        {
            this.iMEIField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string MEID
    {
        get
        {
            return this.mEIDField;
        }
        set
        {
            this.mEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string MAC
    {
        get
        {
            return this.mACField;
        }
        set
        {
            this.mACField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string PairedTerminalPrimeID
    {
        get
        {
            return this.pairedTerminalPrimeIDField;
        }
        set
        {
            this.pairedTerminalPrimeIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public string LastMTBPUTC
    {
        get
        {
            return this.lastMTBPUTCField;
        }
        set
        {
            this.lastMTBPUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string LastMTWSUTC
    {
        get
        {
            return this.lastMTWSUTCField;
        }
        set
        {
            this.lastMTWSUTCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetTerminalsInfoResult
{
    
    private int errorIDField;
    
    private TerminalInfo[] terminalsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public TerminalInfo[] Terminals
    {
        get
        {
            return this.terminalsField;
        }
        set
        {
            this.terminalsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ErrorInfo
{
    
    private int idField;
    
    private string nameField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Description
    {
        get
        {
            return this.descriptionField;
        }
        set
        {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class IGWSInformationResponse
{
    
    private int errorIDField;
    
    private string uTCField;
    
    private string versionField;
    
    private ErrorInfo[] errorCodesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string UTC
    {
        get
        {
            return this.uTCField;
        }
        set
        {
            this.uTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string Version
    {
        get
        {
            return this.versionField;
        }
        set
        {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
    public ErrorInfo[] ErrorCodes
    {
        get
        {
            return this.errorCodesField;
        }
        set
        {
            this.errorCodesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ForwardMessageRecord
{
    
    private int idField;
    
    private string statusUTCField;
    
    private string createUTCField;
    
    private bool isClosedField;
    
    private int stateField;
    
    private string destinationIDField;
    
    private int errorIDField;
    
    private bool errorIDFieldSpecified;
    
    private byte[] rawPayloadField;
    
    private Message payloadField;
    
    private int referenceNumberField;
    
    private bool referenceNumberFieldSpecified;
    
    private string transportField;
    
    private string scheduledSendUTCField;
    
    private string regionNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StatusUTC
    {
        get
        {
            return this.statusUTCField;
        }
        set
        {
            this.statusUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string CreateUTC
    {
        get
        {
            return this.createUTCField;
        }
        set
        {
            this.createUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public bool IsClosed
    {
        get
        {
            return this.isClosedField;
        }
        set
        {
            this.isClosedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public string DestinationID
    {
        get
        {
            return this.destinationIDField;
        }
        set
        {
            this.destinationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorIDSpecified
    {
        get
        {
            return this.errorIDFieldSpecified;
        }
        set
        {
            this.errorIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=7)]
    public byte[] RawPayload
    {
        get
        {
            return this.rawPayloadField;
        }
        set
        {
            this.rawPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public Message Payload
    {
        get
        {
            return this.payloadField;
        }
        set
        {
            this.payloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=9)]
    public int ReferenceNumber
    {
        get
        {
            return this.referenceNumberField;
        }
        set
        {
            this.referenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReferenceNumberSpecified
    {
        get
        {
            return this.referenceNumberFieldSpecified;
        }
        set
        {
            this.referenceNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public string Transport
    {
        get
        {
            return this.transportField;
        }
        set
        {
            this.transportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=11)]
    public string ScheduledSendUTC
    {
        get
        {
            return this.scheduledSendUTCField;
        }
        set
        {
            this.scheduledSendUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=12)]
    public string RegionName
    {
        get
        {
            return this.regionNameField;
        }
        set
        {
            this.regionNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class Message
{
    
    private Field[] fieldsField;
    
    private string nameField;
    
    private int sINField;
    
    private int mINField;
    
    private string isForwardField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public Field[] Fields
    {
        get
        {
            return this.fieldsField;
        }
        set
        {
            this.fieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int SIN
    {
        get
        {
            return this.sINField;
        }
        set
        {
            this.sINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public int MIN
    {
        get
        {
            return this.mINField;
        }
        set
        {
            this.mINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string IsForward
    {
        get
        {
            return this.isForwardField;
        }
        set
        {
            this.isForwardField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class Field
{
    
    private Element[] elementsField;
    
    private Message messageField;
    
    private string nameField;
    
    private string valueField;
    
    private string typeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public Element[] Elements
    {
        get
        {
            return this.elementsField;
        }
        set
        {
            this.elementsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public Message Message
    {
        get
        {
            return this.messageField;
        }
        set
        {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name
    {
        get
        {
            return this.nameField;
        }
        set
        {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Value
    {
        get
        {
            return this.valueField;
        }
        set
        {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Type
    {
        get
        {
            return this.typeField;
        }
        set
        {
            this.typeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class Element
{
    
    private Field[] fieldsField;
    
    private int indexField;
    
    public Element()
    {
        this.indexField = -1;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public Field[] Fields
    {
        get
        {
            return this.fieldsField;
        }
        set
        {
            this.fieldsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    [System.ComponentModel.DefaultValueAttribute(-1)]
    public int Index
    {
        get
        {
            return this.indexField;
        }
        set
        {
            this.indexField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetForwardMessagesResult
{
    
    private int errorIDField;
    
    private ForwardMessageRecord[] messagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public ForwardMessageRecord[] Messages
    {
        get
        {
            return this.messagesField;
        }
        set
        {
            this.messagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ForwardStatus
{
    
    private int forwardMessageIDField;
    
    private bool isClosedField;
    
    private int stateField;
    
    private string stateUTCField;
    
    private int errorIDField;
    
    private bool errorIDFieldSpecified;
    
    private int referenceNumberField;
    
    private bool referenceNumberFieldSpecified;
    
    private string transportField;
    
    private string scheduledSendUTCField;
    
    private string regionNameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ForwardMessageID
    {
        get
        {
            return this.forwardMessageIDField;
        }
        set
        {
            this.forwardMessageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public bool IsClosed
    {
        get
        {
            return this.isClosedField;
        }
        set
        {
            this.isClosedField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int State
    {
        get
        {
            return this.stateField;
        }
        set
        {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public string StateUTC
    {
        get
        {
            return this.stateUTCField;
        }
        set
        {
            this.stateUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorIDSpecified
    {
        get
        {
            return this.errorIDFieldSpecified;
        }
        set
        {
            this.errorIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int ReferenceNumber
    {
        get
        {
            return this.referenceNumberField;
        }
        set
        {
            this.referenceNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ReferenceNumberSpecified
    {
        get
        {
            return this.referenceNumberFieldSpecified;
        }
        set
        {
            this.referenceNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public string Transport
    {
        get
        {
            return this.transportField;
        }
        set
        {
            this.transportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string ScheduledSendUTC
    {
        get
        {
            return this.scheduledSendUTCField;
        }
        set
        {
            this.scheduledSendUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=8)]
    public string RegionName
    {
        get
        {
            return this.regionNameField;
        }
        set
        {
            this.regionNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetForwardStatusesResult
{
    
    private int errorIDField;
    
    private string nextStartUTCField;
    
    private ForwardStatus[] statusesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string NextStartUTC
    {
        get
        {
            return this.nextStartUTCField;
        }
        set
        {
            this.nextStartUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    public ForwardStatus[] Statuses
    {
        get
        {
            return this.statusesField;
        }
        set
        {
            this.statusesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ForwardStatusFilter
{
    
    private int[] forwardMessageIDsField;
    
    private string startUTCField;
    
    private string subaccountIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
    public int[] ForwardMessageIDs
    {
        get
        {
            return this.forwardMessageIDsField;
        }
        set
        {
            this.forwardMessageIDsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string StartUTC
    {
        get
        {
            return this.startUTCField;
        }
        set
        {
            this.startUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string SubaccountID
    {
        get
        {
            return this.subaccountIDField;
        }
        set
        {
            this.subaccountIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ForwardSubmission
{
    
    private int forwardMessageIDField;
    
    private string destinationIDField;
    
    private int errorIDField;
    
    private bool errorIDFieldSpecified;
    
    private ulong userMessageIDField;
    
    private bool userMessageIDFieldSpecified;
    
    private string scheduledSendUTCField;
    
    private int terminalWakeupPeriodField;
    
    private bool terminalWakeupPeriodFieldSpecified;
    
    private System.Nullable<int> oTAMessageSizeField;
    
    private bool oTAMessageSizeFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ForwardMessageID
    {
        get
        {
            return this.forwardMessageIDField;
        }
        set
        {
            this.forwardMessageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string DestinationID
    {
        get
        {
            return this.destinationIDField;
        }
        set
        {
            this.destinationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool ErrorIDSpecified
    {
        get
        {
            return this.errorIDFieldSpecified;
        }
        set
        {
            this.errorIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public ulong UserMessageID
    {
        get
        {
            return this.userMessageIDField;
        }
        set
        {
            this.userMessageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserMessageIDSpecified
    {
        get
        {
            return this.userMessageIDFieldSpecified;
        }
        set
        {
            this.userMessageIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string ScheduledSendUTC
    {
        get
        {
            return this.scheduledSendUTCField;
        }
        set
        {
            this.scheduledSendUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public int TerminalWakeupPeriod
    {
        get
        {
            return this.terminalWakeupPeriodField;
        }
        set
        {
            this.terminalWakeupPeriodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TerminalWakeupPeriodSpecified
    {
        get
        {
            return this.terminalWakeupPeriodFieldSpecified;
        }
        set
        {
            this.terminalWakeupPeriodFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
    public System.Nullable<int> OTAMessageSize
    {
        get
        {
            return this.oTAMessageSizeField;
        }
        set
        {
            this.oTAMessageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OTAMessageSizeSpecified
    {
        get
        {
            return this.oTAMessageSizeFieldSpecified;
        }
        set
        {
            this.oTAMessageSizeFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class SubmitMessagesResult
{
    
    private int errorIDField;
    
    private ForwardSubmission[] submissionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
    public ForwardSubmission[] Submissions
    {
        get
        {
            return this.submissionsField;
        }
        set
        {
            this.submissionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class DelayedSend
{
    
    private bool satelliteSendOnReceiveField;
    
    private string messageExpireUTCField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public bool SatelliteSendOnReceive
    {
        get
        {
            return this.satelliteSendOnReceiveField;
        }
        set
        {
            this.satelliteSendOnReceiveField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageExpireUTC
    {
        get
        {
            return this.messageExpireUTCField;
        }
        set
        {
            this.messageExpireUTCField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ForwardMessage
{
    
    private string destinationIDField;
    
    private ulong userMessageIDField;
    
    private bool userMessageIDFieldSpecified;
    
    private byte[] rawPayloadField;
    
    private Message payloadField;
    
    private string transportTypeField;
    
    private DelayedSend sendOptionsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public string DestinationID
    {
        get
        {
            return this.destinationIDField;
        }
        set
        {
            this.destinationIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public ulong UserMessageID
    {
        get
        {
            return this.userMessageIDField;
        }
        set
        {
            this.userMessageIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UserMessageIDSpecified
    {
        get
        {
            return this.userMessageIDFieldSpecified;
        }
        set
        {
            this.userMessageIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
    public byte[] RawPayload
    {
        get
        {
            return this.rawPayloadField;
        }
        set
        {
            this.rawPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public Message Payload
    {
        get
        {
            return this.payloadField;
        }
        set
        {
            this.payloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string TransportType
    {
        get
        {
            return this.transportTypeField;
        }
        set
        {
            this.transportTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=5)]
    public DelayedSend SendOptions
    {
        get
        {
            return this.sendOptionsField;
        }
        set
        {
            this.sendOptionsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class ReturnMessage
{
    
    private ulong idField;
    
    private string messageUTCField;
    
    private string receiveUTCField;
    
    private int sINField;
    
    private string mobileIDField;
    
    private byte[] rawPayloadField;
    
    private Message payloadField;
    
    private string regionNameField;
    
    private System.Nullable<int> oTAMessageSizeField;
    
    private bool oTAMessageSizeFieldSpecified;
    
    private System.Nullable<int> customerIDField;
    
    private bool customerIDFieldSpecified;
    
    private int transportField;
    
    private System.Nullable<int> mobileOwnerIDField;
    
    private bool mobileOwnerIDFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public ulong ID
    {
        get
        {
            return this.idField;
        }
        set
        {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string MessageUTC
    {
        get
        {
            return this.messageUTCField;
        }
        set
        {
            this.messageUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=2)]
    public string ReceiveUTC
    {
        get
        {
            return this.receiveUTCField;
        }
        set
        {
            this.receiveUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=3)]
    public int SIN
    {
        get
        {
            return this.sINField;
        }
        set
        {
            this.sINField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=4)]
    public string MobileID
    {
        get
        {
            return this.mobileIDField;
        }
        set
        {
            this.mobileIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
    public byte[] RawPayload
    {
        get
        {
            return this.rawPayloadField;
        }
        set
        {
            this.rawPayloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=6)]
    public Message Payload
    {
        get
        {
            return this.payloadField;
        }
        set
        {
            this.payloadField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=7)]
    public string RegionName
    {
        get
        {
            return this.regionNameField;
        }
        set
        {
            this.regionNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
    public System.Nullable<int> OTAMessageSize
    {
        get
        {
            return this.oTAMessageSizeField;
        }
        set
        {
            this.oTAMessageSizeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool OTAMessageSizeSpecified
    {
        get
        {
            return this.oTAMessageSizeFieldSpecified;
        }
        set
        {
            this.oTAMessageSizeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
    public System.Nullable<int> CustomerID
    {
        get
        {
            return this.customerIDField;
        }
        set
        {
            this.customerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool CustomerIDSpecified
    {
        get
        {
            return this.customerIDFieldSpecified;
        }
        set
        {
            this.customerIDFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=10)]
    public int Transport
    {
        get
        {
            return this.transportField;
        }
        set
        {
            this.transportField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=11)]
    public System.Nullable<int> MobileOwnerID
    {
        get
        {
            return this.mobileOwnerIDField;
        }
        set
        {
            this.mobileOwnerIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool MobileOwnerIDSpecified
    {
        get
        {
            return this.mobileOwnerIDFieldSpecified;
        }
        set
        {
            this.mobileOwnerIDFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.9032.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="IGWS")]
public partial class GetReturnMessagesResult
{
    
    private int errorIDField;
    
    private string nextStartUTCField;
    
    private ReturnMessage[] messagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=0)]
    public int ErrorID
    {
        get
        {
            return this.errorIDField;
        }
        set
        {
            this.errorIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Order=1)]
    public string NextStartUTC
    {
        get
        {
            return this.nextStartUTCField;
        }
        set
        {
            this.nextStartUTCField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Order=2)]
    public ReturnMessage[] Messages
    {
        get
        {
            return this.messagesField;
        }
        set
        {
            this.messagesField = value;
        }
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMessagesChannel : IMessages, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MessagesClient : System.ServiceModel.ClientBase<IMessages>, IMessages
{
    
    public MessagesClient()
    {
    }
    
    public MessagesClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MessagesClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessagesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MessagesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public GetReturnMessagesResult GetReturnMessages(string accessID, string password, ReturnMessageFilter filter)
    {
        return base.Channel.GetReturnMessages(accessID, password, filter);
    }
    
    public System.Threading.Tasks.Task<GetReturnMessagesResult> GetReturnMessagesAsync(string accessID, string password, ReturnMessageFilter filter)
    {
        return base.Channel.GetReturnMessagesAsync(accessID, password, filter);
    }
    
    public GetReturnMessagesResult GetSubaccountsReturnMessages(string accessID, string password, string startUTC, bool includeRawPayload, bool includeType)
    {
        return base.Channel.GetSubaccountsReturnMessages(accessID, password, startUTC, includeRawPayload, includeType);
    }
    
    public System.Threading.Tasks.Task<GetReturnMessagesResult> GetSubaccountsReturnMessagesAsync(string accessID, string password, string startUTC, bool includeRawPayload, bool includeType)
    {
        return base.Channel.GetSubaccountsReturnMessagesAsync(accessID, password, startUTC, includeRawPayload, includeType);
    }
    
    public SubmitMessagesResult SubmitForwardMessages(string accessID, string password, ForwardMessage[] messages)
    {
        return base.Channel.SubmitForwardMessages(accessID, password, messages);
    }
    
    public System.Threading.Tasks.Task<SubmitMessagesResult> SubmitForwardMessagesAsync(string accessID, string password, ForwardMessage[] messages)
    {
        return base.Channel.SubmitForwardMessagesAsync(accessID, password, messages);
    }
    
    public SubmitMessagesResult SubmitForwardMessageToMultipleDestinations(string accessID, string password, ForwardMessage message, string[] destinations)
    {
        return base.Channel.SubmitForwardMessageToMultipleDestinations(accessID, password, message, destinations);
    }
    
    public System.Threading.Tasks.Task<SubmitMessagesResult> SubmitForwardMessageToMultipleDestinationsAsync(string accessID, string password, ForwardMessage message, string[] destinations)
    {
        return base.Channel.SubmitForwardMessageToMultipleDestinationsAsync(accessID, password, message, destinations);
    }
    
    public SubmitMessagesResult SubmitMessageCancelations(string accessID, string password, int[] fwMessageIDs)
    {
        return base.Channel.SubmitMessageCancelations(accessID, password, fwMessageIDs);
    }
    
    public System.Threading.Tasks.Task<SubmitMessagesResult> SubmitMessageCancelationsAsync(string accessID, string password, int[] fwMessageIDs)
    {
        return base.Channel.SubmitMessageCancelationsAsync(accessID, password, fwMessageIDs);
    }
    
    public GetForwardStatusesResult GetForwardStatuses(string accessID, string password, ForwardStatusFilter filter)
    {
        return base.Channel.GetForwardStatuses(accessID, password, filter);
    }
    
    public System.Threading.Tasks.Task<GetForwardStatusesResult> GetForwardStatusesAsync(string accessID, string password, ForwardStatusFilter filter)
    {
        return base.Channel.GetForwardStatusesAsync(accessID, password, filter);
    }
    
    public GetForwardMessagesResult GetForwardMessages(string accessID, string password, int[] fwMessageIDs, string subaccountID)
    {
        return base.Channel.GetForwardMessages(accessID, password, fwMessageIDs, subaccountID);
    }
    
    public System.Threading.Tasks.Task<GetForwardMessagesResult> GetForwardMessagesAsync(string accessID, string password, int[] fwMessageIDs, string subaccountID)
    {
        return base.Channel.GetForwardMessagesAsync(accessID, password, fwMessageIDs, subaccountID);
    }
    
    public IGWSInformationResponse IGWSInformation(string accessID, string password, bool getErrorCodes)
    {
        return base.Channel.IGWSInformation(accessID, password, getErrorCodes);
    }
    
    public System.Threading.Tasks.Task<IGWSInformationResponse> IGWSInformationAsync(string accessID, string password, bool getErrorCodes)
    {
        return base.Channel.IGWSInformationAsync(accessID, password, getErrorCodes);
    }
    
    public GetTerminalsInfoResult GetTerminalsInfo(string accessID, string password, string subaccountID, string sinceID, int pageSize)
    {
        return base.Channel.GetTerminalsInfo(accessID, password, subaccountID, sinceID, pageSize);
    }
    
    public System.Threading.Tasks.Task<GetTerminalsInfoResult> GetTerminalsInfoAsync(string accessID, string password, string subaccountID, string sinceID, int pageSize)
    {
        return base.Channel.GetTerminalsInfoAsync(accessID, password, subaccountID, sinceID, pageSize);
    }
    
    public GetBroadcastInfoResult GetBroadcastInfos(string accessID, string password, string subaccountID)
    {
        return base.Channel.GetBroadcastInfos(accessID, password, subaccountID);
    }
    
    public System.Threading.Tasks.Task<GetBroadcastInfoResult> GetBroadcastInfosAsync(string accessID, string password, string subaccountID)
    {
        return base.Channel.GetBroadcastInfosAsync(accessID, password, subaccountID);
    }
    
    public GetSubaccountInfoResult GetSubaccountInfos(string accessID, string password)
    {
        return base.Channel.GetSubaccountInfos(accessID, password);
    }
    
    public System.Threading.Tasks.Task<GetSubaccountInfoResult> GetSubaccountInfosAsync(string accessID, string password)
    {
        return base.Channel.GetSubaccountInfosAsync(accessID, password);
    }
}
namespace IGWS
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessageFilter", Namespace="IGWS")]
    public partial class ReturnMessageFilter : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string StartUTCField;
        
        private bool IncludeRawPayloadField;
        
        private string SubAccountIDField;
        
        private System.Nullable<bool> IncludeTypeField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StartUTC
        {
            get
            {
                return this.StartUTCField;
            }
            set
            {
                this.StartUTCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public bool IncludeRawPayload
        {
            get
            {
                return this.IncludeRawPayloadField;
            }
            set
            {
                this.IncludeRawPayloadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string SubAccountID
        {
            get
            {
                return this.SubAccountIDField;
            }
            set
            {
                this.SubAccountIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.Nullable<bool> IncludeType
        {
            get
            {
                return this.IncludeTypeField;
            }
            set
            {
                this.IncludeTypeField = value;
            }
        }
    }
}
namespace GeneratedNamespace1
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IGWSFault", Namespace="")]
    public partial class IGWSFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int ErrorIDField;
        
        private string ErrorField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ErrorID
        {
            get
            {
                return this.ErrorIDField;
            }
            set
            {
                this.ErrorIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
    }
}
